name: Backend Testing
on:
  pull_request:
  push:
    paths: ['backend/**']
  
env:
  DB_USER: ${{ secrets.DB_USER }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  DB_NAME: testDB
  TOKEN_SCERT: ${{ secrets.TOKEN_SCERT }}
  SERVER_PORT: 5000
  
jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v2
        
      - name: Build Backend 
        run: |
          cd backend
          npm ci
          npm run build --if-present
          
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Test Backend  
        run: |
          cd backend
          npm ci
          npm test
