name: Frontend Testing
on:
  pull_request:
  push:
    paths: ['frontend/**']

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Build Frontend
        run: |
          cd frontend
          npm ci
          npm run build
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Test frontend
        run: |
          cd frontend
          npm ci
          npm test
